### PR TITLE
Make file checks more verbose

### PR DESCRIPTION
**Pull request by justinp**
@ecassady @dwcramer

This is really just a PR to see if you guys are paying attention.

I'm torn between making the shell scripts as simple as possible and making them more verbose.  I can see benefits either way.  Prior to this change, the scripts were as minimalist as possible.  Posterior to the change, they are (arguably) more readable and write to stdout the reason that they responded the way they did.

Once we have a decent, probably collapsible, style for the report, I don't think that the difference in vertical space will matter much.  I just realized while I was testing that I couldn't tell the difference between "remote file not there" and "remote file is different."  Even beyond that, if it was different, there was nothing to say how or why it was different (like "local file has 910 bytes and remote file has 0 bytes").

I think I'm pretty much in favor of this style of scripting, but I wanted to run it by you guys.

Here are some before and after images when the checksum is different to give you an idea.

screen shot 2016-09-16 at 8 49 28 am

screen shot 2016-09-16 at 8 48 41 am

### CODE REVIEW

**Comment by justinp** [comment]
Almost forgot...  I also started messing around with assigning the important values from Scala scope to bash variables in the beginning of the script instead of sprinkling them throughout the script.  I thought this could lead to a different (better?) style where we can just store bash scripts in the build tree (with all the IDE goodness they provide) instead of having them embedded in Scala code.  Then, we could combine them with the Scala-scoped replacements immediately before they're sent to the target host.

I was trying to avoid something like this in the beginning because I wanted more of the code in Scala and less in bash, but I think it's unavoidable that we'll have at least this much, especially if we go with the verbose style above, and we may as well make it as painless as possible.

**Comment by ecassady** [comment]
Ok, I like the more verbose scripting style as a convention.

One suggestion: You could use different exit codes for each different test "failure" and pull the messages up to the scala code instead of having them in the bash scripts. (Obviously you would still have to output debug info like the lengths in the bash script). This would make it easier to externalize messages later. 

This would also allow for different actions based on different test results, such as a producing an error if the file would need to be changed but is not writable. It would also keep exit codes inside the Command classes. test() could return an enumeration value like Perform, Skip, WouldFail, Error. Keeping the exit codes inside test() makes more sense to me especially in a case like this example, where you are actually running more than one bash script in sequence.

**Comment by ecassady** [comment]
+1

**Comment by ecassady** [comment]
I like the idea of making it possible to have the bash scripts in separate source files to take advantage of a bash-aware IDE. You could avoid any magic relating to the replacements by setting them as environment variables. Then you could refer to them anywhere in the script, or show that you expect them by testing them right away at the beginning.

**Comment by justinp** [comment]
RE: exit codes

I couldn't decide if something like that would be worthwhile when I started and I still am not sure.  The problem is that I think each script will have its own set of errors, so trying to generalize them and put the messages in Scala may be futile.

I definitely don't want to have the test script attempt to determine if the perform script will fail (your example was the file is not writable) because there are too many cases to cover and I think the perform script can fail on its own just fine.

I can see a clear difference between Skip, Perform and Error.  Right now Perform and Error are the same case.  We could definitely change that, but the problem I see is that the script could fail in any way with any exit code and so we can't reserve one for our use.  At least not without jumping through all sorts of hoops to make sure no other command returns that exit code.

**Comment by justinp** [comment]
RE: env variables

I like prepending them to the script (at least for now) because the script is written as part of the report and you have the full text to run manually if you want.  If we get away from presenting the script in the report the way it is now, we'll have to rethink it.

**Review by ecassady — APPROVED** [review]
Trying out the new (to me at least) formal PR review feature of github.

**Comment by dwcramer** [comment]
+1 for more verbose. 
Being able to develop scripts in a bash ide would be a big help, but I wonder how often that will be feasible if the the shell script code is tied to the context of the jibe playbook.

**Comment by ecassady** [comment]
RE: exit codes
A couple of comments:
1) I'm not suggesting generalizing them, just pulling them out of the bash script. Each call to ssh() (or sequence of them in one test() or perform()) would have its own optional mapping logic. By default, exit code 0 would be Skip, 1 would be Perform, and there would be no detailed message relating to the Perform decision. That would be the only built-in generalization.
2) Because I'm not suggesting generalizing exit codes, I don't think your concern about Error would be an issue. You could use any non-zero exit code for an Error condition (which, to be sure we're talking about the same thing, I was intending to mean a fatal error that should cause execution to stop)
3) I can still see value in a WouldFail exit code, in cases where you want to prevent the perform step from being attempted (i.e. something that may have multiple effects that cannot be rolled back) but the host would be in a bad state if you just Skipped it, so processing should stop.  Maybe this is really the same thing as an Error result, though. This seems similar to the whole reason for test() in the first place, as we were discussing yesterday.

**Review by dwcramer — APPROVED** [review]

**Comment by justinp** [comment]
I get what you're saying about the exit codes now.  I think we'll just have to play that by ear.  I was thinking of making the Command interfaces return true/false for (skip, perform) and throw an exception for error.  There could still be some logic to determine what's a success and what's a failure.  I was thinking about putting that into the bash script for now just to keep from spreading the logic around.

I'm going to go ahead and merge this one now and remember to rethink the other stuff you brought up later.

**Pull request merged**
